apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJsb2tlc2gxODA5Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJiRzlyWlhOb1lXMWlZWFJwT2t4dmEyVnphRUF4T0RBNU1EQT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson